org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=F:\\include\\jdk-21.0.2

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.7
loader_version=0.16.9
# Mod Properties
mod_version=1.2.7
maven_group=com.example
archives_base_name=LeavesHack

# Proxy Configuration (127.0.0.1:15236)
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=15236
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=15236
# Dependencies

# Meteor (https://maven.meteordev.org)
meteor_version=1.21.4-SNAPSHOT
baritone_version=1.21.4
